name: 'shopify_source'
version: '0.6.0'
config-version: 2

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  shopify_source:
    +schema: stg_shopify
    +materialized: table
    tmp:
      +materialized: view

vars:
  shopify_source:
    customer_source: "{{ source('shopify','customer') }}"
    order_line_refund_source: "{{ source('shopify','order_line_refund') }}"
    order_line_source: "{{ source('shopify','order_line') }}"
    order_source: "{{ source('shopify','order') }}"
    product_source: "{{ source('shopify','product') }}"
    product_variant_source: "{{ source('shopify','product_variant') }}"
    transaction_source: "{{ source('shopify','transaction') }}"
    refund_source: "{{ source('shopify','refund') }}"
    order_adjustment_source: "{{ source('shopify','order_adjustment') }}"
    metafield_source: "{{ source('shopify', 'metafield') }}"
    customer_pass_through_columns: []
    order_line_refund_pass_through_columns: []
    order_line_pass_through_columns: []
    order_pass_through_columns: []
    product_pass_through_columns: []
    product_variant_pass_through_columns: []
    transaction_pass_through_columns: []
    metafield_pass_through_columns: []

    shopify__using_order_adjustment: true
    shopify__using_order_line_refund: true
    shopify__using_refund: true
