{% macro get_shop_columns() %}

{% set columns = [
    {"name": "_fivetran_deleted", "datatype": dbt.type_boolean()},
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "address_1", "datatype": dbt.type_string()},
    {"name": "address_2", "datatype": dbt.type_string()},
    {"name": "checkout_api_supported", "datatype": dbt.type_boolean()},
    {"name": "city", "datatype": dbt.type_string()},
    {"name": "cookie_consent_level", "datatype": dbt.type_string()},
    {"name": "country", "datatype": dbt.type_string()},
    {"name": "country_code", "datatype": dbt.type_string()},
    {"name": "country_name", "datatype": dbt.type_string()},
    {"name": "county_taxes", "datatype": dbt.type_boolean()},
    {"name": "created_at", "datatype": dbt.type_timestamp()},
    {"name": "currency", "datatype": dbt.type_string()},
    {"name": "customer_email", "datatype": dbt.type_string()},
    {"name": "domain", "datatype": dbt.type_string()},
    {"name": "eligible_for_card_reader_giveaway", "datatype": dbt.type_boolean()},
    {"name": "eligible_for_payments", "datatype": dbt.type_boolean()},
    {"name": "email", "datatype": dbt.type_string()},
    {"name": "enabled_presentment_currencies", "datatype": dbt.type_string()},
    {"name": "google_apps_domain", "datatype": dbt.type_string()},
    {"name": "google_apps_login_enabled", "datatype": dbt.type_boolean()},
    {"name": "has_discounts", "datatype": dbt.type_boolean()},
    {"name": "has_gift_cards", "datatype": dbt.type_boolean()},
    {"name": "has_storefront", "datatype": dbt.type_boolean()},
    {"name": "iana_timezone", "datatype": dbt.type_string()},
    {"name": "id", "datatype": dbt.type_int()},
    {"name": "latitude", "datatype": dbt.type_float()},
    {"name": "longitude", "datatype": dbt.type_float()},
    {"name": "money_format", "datatype": dbt.type_string()},
    {"name": "money_in_emails_format", "datatype": dbt.type_string()},
    {"name": "money_with_currency_format", "datatype": dbt.type_string()},
    {"name": "money_with_currency_in_emails_format", "datatype": dbt.type_string()},
    {"name": "myshopify_domain", "datatype": dbt.type_string()},
    {"name": "name", "datatype": dbt.type_string()},
    {"name": "password_enabled", "datatype": dbt.type_boolean()},
    {"name": "phone", "datatype": dbt.type_string()},
    {"name": "plan_display_name", "datatype": dbt.type_string()},
    {"name": "plan_name", "datatype": dbt.type_string()},
    {"name": "pre_launch_enabled", "datatype": dbt.type_boolean()},
    {"name": "primary_locale", "datatype": dbt.type_string()},
    {"name": "province", "datatype": dbt.type_string()},
    {"name": "province_code", "datatype": dbt.type_string()},
    {"name": "requires_extra_payments_agreement", "datatype": dbt.type_boolean()},
    {"name": "setup_required", "datatype": dbt.type_boolean()},
    {"name": "shop_owner", "datatype": dbt.type_string()},
    {"name": "source", "datatype": dbt.type_string()},
    {"name": "tax_shipping", "datatype": dbt.type_boolean()},
    {"name": "taxes_included", "datatype": dbt.type_boolean()},
    {"name": "timezone", "datatype": dbt.type_string()},
    {"name": "updated_at", "datatype": dbt.type_timestamp()},
    {"name": "weight_unit", "datatype": dbt.type_string()},
    {"name": "zip", "datatype": dbt.type_string()}
] %}

{{ return(columns) }}

{% endmacro %}


{% macro get_graphql_shop_columns() %}

{% set columns = [
    {"name": "_fivetran_deleted", "datatype": dbt.type_boolean()},
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "account_owner_id", "datatype": dbt.type_int()},
    {"name": "billing_address_address_1", "datatype": dbt.type_string()},
    {"name": "billing_address_address_2", "datatype": dbt.type_string()},
    {"name": "billing_address_city", "datatype": dbt.type_string()},
    {"name": "billing_address_company", "datatype": dbt.type_string()},
    {"name": "billing_address_coordinates_validated", "datatype": dbt.type_boolean()},
    {"name": "billing_address_country", "datatype": dbt.type_string()},
    {"name": "billing_address_country_code_v_2", "datatype": dbt.type_string()},
    {"name": "billing_address_id", "datatype": dbt.type_int()},
    {"name": "billing_address_latitude", "datatype": dbt.type_float()},
    {"name": "billing_address_longitude", "datatype": dbt.type_float()},
    {"name": "billing_address_phone", "datatype": dbt.type_string()},
    {"name": "billing_address_province", "datatype": dbt.type_string()},
    {"name": "billing_address_province_code", "datatype": dbt.type_string()},
    {"name": "billing_address_zip", "datatype": dbt.type_string()},
    {"name": "checkout_api_supported", "datatype": dbt.type_boolean()},
    {"name": "contact_email", "datatype": dbt.type_string()},
    {"name": "countries_in_shipping_zones_country_codes", "datatype": dbt.type_string()},
    {"name": "countries_in_shipping_zones_include_rest_of_world", "datatype": dbt.type_boolean()},
    {"name": "created_at", "datatype": dbt.type_timestamp()},
    {"name": "currency_code", "datatype": dbt.type_string()},
    {"name": "currency_formats_money_format", "datatype": dbt.type_string()},
    {"name": "currency_formats_money_in_emails_format", "datatype": dbt.type_string()},
    {"name": "currency_formats_money_with_currency_format", "datatype": dbt.type_string()},
    {"name": "currency_formats_money_with_currency_in_emails_format", "datatype": dbt.type_string()},
    {"name": "customer_accounts", "datatype": dbt.type_string()},
    {"name": "customer_accounts_login_links_visible_on_storefront_checkout", "datatype": dbt.type_boolean()},
    {"name": "customer_accounts_login_required_at_checkout", "datatype": dbt.type_boolean()},
    {"name": "customer_accounts_url", "datatype": dbt.type_string()},
    {"name": "customer_accounts_version", "datatype": dbt.type_string()},
    {"name": "description", "datatype": dbt.type_string()},
    {"name": "email", "datatype": dbt.type_string()},
    {"name": "enabled_presentment_currencies", "datatype": dbt.type_string()},
    {"name": "features_avalara_avatax", "datatype": dbt.type_boolean()},
    {"name": "features_branding", "datatype": dbt.type_string()},
    {"name": "features_bundles_eligible_for_bundles", "datatype": dbt.type_boolean()},
    {"name": "features_bundles_ineligibility_reason", "datatype": dbt.type_string()},
    {"name": "features_bundles_sells_bundles", "datatype": dbt.type_boolean()},
    {"name": "features_captcha", "datatype": dbt.type_boolean()},
    {"name": "features_cart_transform_eligible_operations_expand_operation", "datatype": dbt.type_boolean()},
    {"name": "features_cart_transform_eligible_operations_merge_operation", "datatype": dbt.type_boolean()},
    {"name": "features_cart_transform_eligible_operations_update_operation", "datatype": dbt.type_boolean()},
    {"name": "features_dynamic_remarketing", "datatype": dbt.type_boolean()},
    {"name": "features_eligible_for_subscription_migration", "datatype": dbt.type_boolean()},
    {"name": "features_eligible_for_subscriptions", "datatype": dbt.type_boolean()},
    {"name": "features_gift_cards", "datatype": dbt.type_boolean()},
    {"name": "features_harmonized_system_code", "datatype": dbt.type_boolean()},
    {"name": "features_international_price_overrides", "datatype": dbt.type_boolean()},
    {"name": "features_international_price_rules", "datatype": dbt.type_boolean()},
    {"name": "features_legacy_subscription_gateway_enabled", "datatype": dbt.type_boolean()},
    {"name": "features_live_view", "datatype": dbt.type_boolean()},
    {"name": "features_paypal_express_subscription_gateway_status", "datatype": dbt.type_string()},
    {"name": "features_reports", "datatype": dbt.type_boolean()},
    {"name": "features_sells_subscriptions", "datatype": dbt.type_boolean()},
    {"name": "features_show_metrics", "datatype": dbt.type_boolean()},
    {"name": "features_storefront", "datatype": dbt.type_boolean()},
    {"name": "iana_timezone", "datatype": dbt.type_string()},
    {"name": "id", "datatype": dbt.type_int()},
    {"name": "marketing_sms_consent_enabled_at_checkout", "datatype": dbt.type_boolean()},
    {"name": "myshopify_domain", "datatype": dbt.type_string()},
    {"name": "name", "datatype": dbt.type_string()},
    {"name": "order_number_format_prefix", "datatype": dbt.type_string()},
    {"name": "order_number_format_suffix", "datatype": dbt.type_string()},
    {"name": "password_enabled", "datatype": dbt.type_boolean()},
    {"name": "payment_settings_supported_digital_wallets", "datatype": dbt.type_string()},
    {"name": "plan_display_name", "datatype": dbt.type_string()},
    {"name": "plan_partner_development", "datatype": dbt.type_boolean()},
    {"name": "plan_shopify_plus", "datatype": dbt.type_boolean()},
    {"name": "primary_domain_host", "datatype": dbt.type_string()},
    {"name": "primary_domain_id", "datatype": dbt.type_int()},
    {"name": "primary_domain_localization_alternate_locales", "datatype": dbt.type_string()},
    {"name": "primary_domain_localization_country", "datatype": dbt.type_string()},
    {"name": "primary_domain_localization_default_locale", "datatype": dbt.type_string()},
    {"name": "primary_domain_ssl_enabled", "datatype": dbt.type_boolean()},
    {"name": "primary_domain_url", "datatype": dbt.type_string()},
    {"name": "resource_limits_location_limit", "datatype": dbt.type_int()},
    {"name": "resource_limits_max_product_options", "datatype": dbt.type_int()},
    {"name": "resource_limits_max_product_variants", "datatype": dbt.type_int()},
    {"name": "resource_limits_redirect_limit_reached", "datatype": dbt.type_boolean()},
    {"name": "rich_text_editor_url", "datatype": dbt.type_string()},
    {"name": "setup_required", "datatype": dbt.type_boolean()},
    {"name": "ships_to_countries", "datatype": dbt.type_string()},
    {"name": "shop_owner_name", "datatype": dbt.type_string()},
    {"name": "tax_shipping", "datatype": dbt.type_boolean()},
    {"name": "taxes_included", "datatype": dbt.type_boolean()},
    {"name": "timezone_abbreviation", "datatype": dbt.type_string()},
    {"name": "timezone_offset", "datatype": dbt.type_string()},
    {"name": "timezone_offset_minutes", "datatype": dbt.type_int()},
    {"name": "transactional_sms_disabled", "datatype": dbt.type_boolean()},
    {"name": "unit_system", "datatype": dbt.type_string()},
    {"name": "updated_at", "datatype": dbt.type_timestamp()},
    {"name": "url", "datatype": dbt.type_string()},
    {"name": "weight_unit", "datatype": dbt.type_string()}
] %}

{{ return(columns) }}

{% endmacro %}