with base as (

    select * 
    from {{ ref('stg_shopify_gql__order_tmp') }}
),

fields as (

    select
        {{
            fivetran_utils.fill_staging_columns(
                source_columns=adapter.get_columns_in_relation(ref('stg_shopify_gql__order_tmp')),
                staging_columns=get_graphql_order_columns()
            )
        }}
        {{ fivetran_utils.source_relation(
            union_schema_variable='shopify_union_schemas', 
            union_database_variable='shopify_union_databases') 
        }}
    from base
),

final as (
    
    select 
        id as order_id,
        staff_member_id as user_id,
        {# total_discounts broken out #}
        total_discounts_set_pres_amount,
        total_discounts_set_pres_currency_code,
        total_discounts_set_shop_amount,
        total_discounts_set_shop_currency_code,
        {# no total_line_items_price - need to join in #}
        {# total_price broken out #}
        total_price_set_pres_amount,
        total_price_set_pres_currency_code,
        total_price_set_shop_amount,
        total_price_set_shop_currency_code,
        {# total_tax broken out #}
        total_tax_set_pres_amount,
        total_tax_set_pres_currency_code,
        total_tax_set_shop_amount,
        total_tax_set_shop_currency_code,
        source_name,
        {# subtotal_price broken out #}
        subtotal_price_set_pres_amount,
        subtotal_price_set_pres_currency_code,
        subtotal_price_set_shop_amount,
        subtotal_price_set_shop_currency_code,
        taxes_included as has_taxes_included,
        total_weight,
        {# total_tip_received broken out #}
        total_tip_received_set_pres_amount,
        total_tip_received_set_pres_currency_code,
        total_tip_received_set_shop_amount,
        total_tip_received_set_shop_currency_code,
        {# no landing_site_base_url - maybe join in customer_visit.landing_page #}
        location_id,
        name,
        note,
        {# number and order_number aren't included rn #}
        cancel_reason,
        {# cart_token and checkout_token are deprecated #}
        {{ shopify_source.fivetran_convert_timezone(column='cast(created_at as ' ~ dbt.type_timestamp() ~ ')', target_tz=var('shopify_timezone', "UTC"), source_tz="UTC") }} as created_timestamp,
        {{ shopify_source.fivetran_convert_timezone(column='cast(cancelled_at as ' ~ dbt.type_timestamp() ~ ')', target_tz=var('shopify_timezone', "UTC"), source_tz="UTC") }} as cancelled_timestamp,
        {{ shopify_source.fivetran_convert_timezone(column='cast(closed_at as ' ~ dbt.type_timestamp() ~ ')', target_tz=var('shopify_timezone', "UTC"), source_tz="UTC") }} as closed_timestamp,
        {{ shopify_source.fivetran_convert_timezone(column='cast(processed_at as ' ~ dbt.type_timestamp() ~ ')', target_tz=var('shopify_timezone', "UTC"), source_tz="UTC") }} as processed_timestamp,
        {{ shopify_source.fivetran_convert_timezone(column='cast(updated_at as ' ~ dbt.type_timestamp() ~ ')', target_tz=var('shopify_timezone', "UTC"), source_tz="UTC") }} as updated_timestamp,
        currency_code as currency,
        customer_id,
        lower(email) as email,
        lower(display_financial_status) as financial_status, -- match rest API casing
        lower(display_fulfillment_status) as fulfillment_status, -- match rest API casing
        {# no referring_site - join with customer_visit.referrer_url #}
        billing_address_address_1,
        billing_address_address_2,
        billing_address_city,
        billing_address_company,
        billing_address_country,
        billing_address_country_code,
        billing_address_first_name,
        billing_address_last_name,
        billing_address_latitude,
        billing_address_longitude,
        billing_address_name,
        billing_address_phone,
        billing_address_province,
        billing_address_province_code,
        billing_address_zip,
        client_ip as browser_ip,
        {# total_shipping_price broken out #}
        total_shipping_price_set_pres_amount,
        total_shipping_price_set_pres_currency_code,
        total_shipping_price_set_shop_amount,
        total_shipping_price_set_shop_currency_code,
        shipping_address_address_1,
        shipping_address_address_2,
        shipping_address_city,
        shipping_address_company,
        shipping_address_country,
        shipping_address_country_code,
        shipping_address_first_name,
        shipping_address_last_name,
        shipping_address_latitude,
        shipping_address_longitude,
        shipping_address_name,
        shipping_address_phone,
        shipping_address_province,
        shipping_address_province_code,
        shipping_address_zip,
        {# token is deprecated #}
        app_id,
        {# no checkout_id #}
        {# no client_details_user_agent #}
        customer_locale,
        status_page_url as order_status_url,
        presentment_currency_code as presentment_currency,
        test as is_test_order,
        _fivetran_deleted as is_deleted,
        customer_accepts_marketing as buyer_accepts_marketing,
        confirmed as is_confirmed,
        {{ shopify_source.fivetran_convert_timezone(column='cast(_fivetran_synced as ' ~ dbt.type_timestamp() ~ ')', target_tz=var('shopify_timezone', "UTC"), source_tz="UTC") }} as _fivetran_synced,
        source_relation

        {{ fivetran_utils.fill_pass_through_columns('order_pass_through_columns') }}

        {# TODO: remove from here and macro for passthru var
        app_icon_alt_text,
        app_icon_height,
        app_icon_id,
        app_icon_url,
        app_icon_width,
        app_name,
        billing_address_coordinates_validated,
        billing_address_id,
        billing_address_matches_shipping_address,
        billing_address_timezone,
        billing_address_validation_result_summary,
        can_mark_as_paid,
        can_notify_customer,
        cancellation_staff_note,
        capturable,
        cart_discount_amount_set_pres_amount,
        cart_discount_amount_set_pres_currency_code,
        cart_discount_amount_set_shop_amount,
        cart_discount_amount_set_shop_currency_code,
        channel_information_channel_definition_channel_name,
        channel_information_channel_definition_handle,
        channel_information_channel_definition_id,
        channel_information_channel_definition_is_marketplace,
        channel_information_channel_definition_sub_channel_name,
        channel_information_channel_definition_svg_icon,
        channel_information_channel_id,
        channel_information_id,
        closed,
        confirmation_number,
        current_cart_discount_amount_set_pres_amount,
        current_cart_discount_amount_set_pres_currency_code,
        current_cart_discount_amount_set_shop_amount,
        current_cart_discount_amount_set_shop_currency_code,
        current_shipping_price_set_pres_amount,
        current_shipping_price_set_pres_currency_code,
        current_shipping_price_set_shop_amount,
        current_shipping_price_set_shop_currency_code,
        current_subtotal_line_items_quantity,
        current_subtotal_price_set_pres_amount,
        current_subtotal_price_set_pres_currency_code,
        current_subtotal_price_set_shop_amount,
        current_subtotal_price_set_shop_currency_code,
        current_total_additional_fees_set_pres_amount,
        current_total_additional_fees_set_pres_currency_code,
        current_total_additional_fees_set_shop_amount,
        current_total_additional_fees_set_shop_currency_code,
        current_total_discounts_set_pres_amount,
        current_total_discounts_set_pres_currency_code,
        current_total_discounts_set_shop_amount,
        current_total_discounts_set_shop_currency_code,
        current_total_duties_set_pres_amount,
        current_total_duties_set_pres_currency_code,
        current_total_duties_set_shop_amount,
        current_total_duties_set_shop_currency_code,
        current_total_price_set_pres_amount,
        current_total_price_set_pres_currency_code,
        current_total_price_set_shop_amount,
        current_total_price_set_shop_currency_code,
        current_total_tax_set_pres_amount,
        current_total_tax_set_pres_currency_code,
        current_total_tax_set_shop_amount,
        current_total_tax_set_shop_currency_code,
        current_total_weight,
        customer_journey_summary_customer_order_index,
        customer_journey_summary_days_to_conversion,
        customer_journey_summary_ready,
        discount_code,
        display_address_address_1,
        display_address_address_2,
        display_address_city,
        display_address_company,
        display_address_coordinates_validated,
        display_address_country,
        display_address_country_code,
        display_address_first_name,
        display_address_id,
        display_address_last_name,
        display_address_latitude,
        display_address_longitude,
        display_address_name,
        display_address_phone,
        display_address_province,
        display_address_province_code,
        display_address_timezone,
        display_address_validation_result_summary,
        display_address_zip,
        duties_included,
        edited,
        estimated_taxes,
        fulfillable,
        fully_paid,
        has_timeline_comment,
        merchant_business_entity_company_name,
        merchant_business_entity_display_name,
        merchant_business_entity_id,
        merchant_business_entity_primary,
        merchant_editable,
        merchant_editable_errors,
        merchant_of_record_app_icon_alt_text,
        merchant_of_record_app_icon_height,
        merchant_of_record_app_icon_id,
        merchant_of_record_app_icon_url,
        merchant_of_record_app_icon_width,
        merchant_of_record_app_id,
        merchant_of_record_app_name,
        net_payment_set_pres_amount,
        net_payment_set_pres_currency_code,
        net_payment_set_shop_amount,
        net_payment_set_shop_currency_code,
        original_total_additional_fees_set_pres_amount,
        original_total_additional_fees_set_pres_currency_code,
        original_total_additional_fees_set_shop_amount,
        original_total_additional_fees_set_shop_currency_code,
        original_total_duties_set_pres_amount,
        original_total_duties_set_pres_currency_code,
        original_total_duties_set_shop_amount,
        original_total_duties_set_shop_currency_code,
        original_total_price_set_pres_amount,
        original_total_price_set_pres_currency_code,
        original_total_price_set_shop_amount,
        original_total_price_set_shop_currency_code,
        payment_gateway_names,
        phone,
        po_number,
        purchasing_entity_company_contact_id,
        purchasing_entity_company_id,
        purchasing_entity_customer_id,
        refund_discrepancy_set_pres_amount,
        refund_discrepancy_set_pres_currency_code,
        refund_discrepancy_set_shop_amount,
        refund_discrepancy_set_shop_currency_code,
        refundable,
        registered_source_url,
        requires_shipping,
        restockable,
        return_status,
        shipping_address_coordinates_validated,
        shipping_address_id,
        shipping_address_timezone,
        shipping_address_validation_result_summary,
        shopify_protect_eligibility_status,
        shopify_protect_status,
        source_identifier,
        subtotal_line_items_quantity,
        tax_exempt,
        total_capturable_set_pres_amount,
        total_capturable_set_pres_currency_code,
        total_capturable_set_shop_amount,
        total_capturable_set_shop_currency_code,
        total_cash_rounding_adj_set_payment_set_pres_amount,
        total_cash_rounding_adj_set_payment_set_pres_currency_code,
        total_cash_rounding_adj_set_payment_set_shop_amount,
        total_cash_rounding_adj_set_payment_set_shop_currency_code,
        total_cash_rounding_adj_set_refund_set_pres_amount,
        total_cash_rounding_adj_set_refund_set_pres_currency_code,
        total_cash_rounding_adj_set_refund_set_shop_amount,
        total_cash_rounding_adj_set_refund_set_shop_currency_code,
        total_outstanding_set_pres_amount,
        total_outstanding_set_pres_currency_code,
        total_outstanding_set_shop_amount,
        total_outstanding_set_shop_currency_code,
        total_received_set_pres_amount,
        total_received_set_pres_currency_code,
        total_received_set_shop_amount,
        total_received_set_shop_currency_code,
        total_refunded_set_pres_amount,
        total_refunded_set_pres_currency_code,
        total_refunded_set_shop_amount,
        total_refunded_set_shop_currency_code,
        total_refunded_shipping_set_pres_amount,
        total_refunded_shipping_set_pres_currency_code,
        total_refunded_shipping_set_shop_amount,
        total_refunded_shipping_set_shop_currency_code,
        unpaid #}

    from fields
)

select *
from final
where not coalesce(is_test_order, false)
and not coalesce(is_deleted, false)