with source as (

    select * from {{ source('shopify', 'abandoned_checkout') }}

),

renamed as (

    select
        id as abandoned_checkout_id,
        user_id,
        location_id,
        customer_id,
        token,
        cart_token,
        email,
        gateway,
        buyer_accepts_marketing,
        updated_at as updated_timestamp,
        created_at as created_timestamp,
        note,
        referring_site,
        subtotal_price,
        total_discounts,
        total_line_items_price,
        total_price,
        total_tax,
        total_weight,
        taxes_included,
        currency,
        completed_at as completed_timestamp,
        closed_at as closed_timestamp,
        source_identifier,
        source_url,
        device_id,
        phone,
        customer_locale,
        abandoned_checkout_url,
        name,
        source,
        source_name,
        shipping_line,
        shipping_address_name,
        shipping_address_first_name,
        shipping_address_last_name,
        shipping_address_company,
        shipping_address_phone,
        shipping_address_address_1,
        shipping_address_address_2,
        shipping_address_city,
        shipping_address_country,
        shipping_address_country_code,
        shipping_address_province,
        shipping_address_province_code,
        shipping_address_zip,
        shipping_address_latitude,
        shipping_address_longitude,
        billing_address_name,
        billing_address_first_name,
        billing_address_last_name,
        billing_address_company,
        billing_address_phone,
        billing_address_address_1,
        billing_address_address_2,
        billing_address_city,
        billing_address_country,
        billing_address_country_code,
        billing_address_province,
        billing_address_province_code,
        billing_address_zip,
        billing_address_latitude,
        billing_address_longitude,
        applied_discount_description,
        applied_discount_value_type,
        applied_discount_value,
        applied_discount_amount,
        applied_discount_title,
        applied_discount_non_applicable_reason,
        applied_discount_applicable,
        shipping_rate_id,
        shipping_rate_price,
        shipping_rate_title,
        credit_card_number,
        credit_card_first_name,
        credit_card_last_name,
        credit_card_month,
        credit_card_year,
        credit_card_verification_value,
        landing_site_base_url,
        _fivetran_synced

    from source

)

select * from renamed

